### ISSUE TITLE
Can't sign in...

### ISSUE THREAD

**Issue by yonilivne** [yonbergman/nomex#1]
@yonbergman 
Hey man,

I can't sign in to edit my song. I get this error:

![screen shot 2016-04-14 at 11 35 39 am](https://cloud.githubusercontent.com/assets/2103687/14521988/10469306-0235-11e6-823a-ec8752ab541b.png)

I'm logged in to Facebook.

Cheers,
Yoni

**Comment by yonbergman** [comment]
What url were you using? 
https://nomex.herokuapp.com/ ?

**Comment by yonilivne** [comment]
I was using: http://yonbergman.github.io/nomex/
With this new URL i can't sign in finally. But how do I change my song? Do I need a special permission?

Thanks :)

**Comment by yonbergman** [comment]
Ask Keshet for assistance, you might not have control to edit your song
(legacy stuff)
